### ISSUE TITLE
 Error al crear un recibo

### ISSUE THREAD

**Issue by andres53016** [tryton-ar/account_voucher_ar#25]
Hola, cuando completo el campo moneda y busca las facturas pendientes y los créditos me salta el siguiente error en la versión 4.8:

> Traceback (most recent call last):
>   File "/trytond/wsgi.py", line 71, in dispatch_request
>     return endpoint(request, **request.view_args)
>   File "/trytond/protocols/dispatcher.py", line 41, in rpc
>     request, database_name, *request.rpc_params)
>   File "/trytond/wsgi.py", line 42, in auth_required
>     return wrapped(*args, **kwargs)
>   File "/trytond/protocols/wrappers.py", line 122, in wrapper
>     return func(request, pool, *args, **kwargs)
>   File "/trytond/protocols/dispatcher.py", line 172, in _dispatch
>     result = rpc.result(meth(inst, *c_args, **c_kwargs))
>   File "/trytond/model/modelview.py", line 679, in on_change
>     method()
>   File "/trytond/model/modelview.py", line 84, in wrapper
>     result = func(self, *args, **kwargs)
>   File "/trytond/model/fields/field.py", line 114, in wrapper
>     return func(self, *args, **kwargs)
>   File "/trytond/modules/account_voucher_ar/account_voucher_ar.py", line 193, in on_change_currency
>     self.add_lines()
>   File "/trytond/modules/account_voucher_ar/account_voucher_ar.py", line 254, in add_lines
>     amount_residual = abs(line.amount_residual)
>   File "/trytond/model/modelstorage.py", line 1466, in __getattr__
>     read_data = self.read(list(ids), ffields.keys())
>   File "/trytond/model/modelsql.py", line 832, in read
>     getter_results = field.get(ids, cls, field_list, values=result)
>   File "/trytond/model/fields/function.py", line 102, in get
>     return dict((name, call(name)) for name in names)
>   File "/trytond/model/fields/function.py", line 102, in <genexpr>
>     return dict((name, call(name)) for name in names)
>   File "/trytond/model/fields/function.py", line 94, in call
>     return method(records, name)
>   File "/trytond/modules/account_voucher_ar/move.py", line 47, in get_amount_residual
>     if payment.voucher.state == 'posted':
> AttributeError: 'NoneType' object has no attribute 'state'

Busque si había algo mal en los otros recibos o en las facturas, pero no encuentro nada mal, habría alguna forma de debuggear para saber que línea de voucher_payments es la que genera la excepción.

Saludos, Pablo.

**Comment by andres53016** [comment]
Pude debuggear y lo raro que la línea que me generaba error era un registro en account_voucher_line, donde la mismo no estaba asociado a un voucher. Probe generar en borrador y eliminar el recibo, pero el mismo elimino el recibo y sus lineas en account_voucher_line. No se como pudo ocurrir.
