### ISSUE TITLE
Error con el parsing de XML

### ISSUE THREAD

**Issue by MateoDaruich** [tryton-ar/account_voucher_ar#36]
Al intentar activar el modulo en la branch de 6.6 en su version mas reciente, aparece este error.

Python 3.10.12
Trytond 6.6.14
Ubuntu 22.04.3
PostgreSQL 14.9

```
Traceback (most recent call last):
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 464, in parse_xmlstream
    self.sax_parser.parse(source)
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.10/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 468, in EndElement
  File "/usr/lib/python3.10/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 519, in endElement
    self.taghandler = self.taghandler.endElement(name)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 314, in endElement
    self.mh.import_record(
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 695, in import_record
    self.create_records(model, [values], [fs_id])
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 701, in create_records
    records = Model.create(vlist)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/ir/ui/view.py", line 209, in create
    views = super(View, cls).create(vlist)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/model/modelsql.py", line 239, in wrapper
    return func(cls, *args, **kwargs)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/model/modelsql.py", line 878, in create
    cls._validate(sub_records)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/model/modelstorage.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/model/modelstorage.py", line 1547, in _validate
    cls.validate(records)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/ir/ui/view.py", line 135, in validate
    cls.check_xml(views)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/ir/ui/view.py", line 153, in check_xml
    raise XMLError(
trytond.ir.ui.view.XMLError: Invalid XML for view "account.voucher.line.paymode (Tree)". - <string>:4:0:ERROR:RELAXNGV:RELAXNG_ERR_INVALIDATTR: Invalid attribute width for element button

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tryton/.local/bin/trytond-admin", line 31, in <module>
    admin.run(options)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/admin.py", line 57, in run
    pool.init(update=options.update, lang=list(lang),
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/pool.py", line 165, in init
    restart = not load_modules(
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/modules/__init__.py", line 454, in load_modules
    _load_modules(update)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/modules/__init__.py", line 422, in _load_modules
    load_module_graph(graph, pool, update, lang)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/modules/__init__.py", line 255, in load_module_graph
    tryton_parser.parse_xmlstream(fp)
  File "/home/tryton/.local/lib/python3.10/site-packages/trytond/convert.py", line 466, in parse_xmlstream
    raise ParsingError("in %s" % self.current_state()) from e
trytond.convert.ParsingError: in record 'account_voucher_ar.pay_lines_view_tree'
```

**Comment by mariomop** [comment]
Al parecer el atributo 'width' no se reconoce hasta versiones posteriores a 6.6
Removido en commit
